all:
	c++ Major_Tom.cpp ../Packets/EBUPacketAnalogOut.cpp ../Packets/EBURelayPacket.cpp ../EBU/EBUManager.cpp ../Packets/CawlPacket.cpp ../Netapi/CawlSocket.cpp ../Netapi/Host.cpp -L/usr/local/lib -lsctp -lpthread -o runMajor

