all:
	c++ Ground_control.cpp ../Netapi/CawlSocket.cpp ../Packets/CawlPacket.cpp ../Packets/EBUPacketAnalogOut.cpp ../EBU/EBUManager.cpp ../Packets/EBURelayPacket.cpp ../Netapi/Host.cpp -L/usr/local/lib -lsctp -lpthread -o utput.o

