all:
	c++ Ground.cpp ../Netapi/Host.cpp ../Netapi/CawlSocket.cpp ../Packets/CawlPacket.cpp ../Packets/EBUPacketAnalogOut.cpp ../Packets/SimPack.cpp ../Simulator/Sim.cpp -L/usr/local/lib -lsctp -o runGround

